// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace solution.model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class PositionKey : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"PositionKey\",\"namespace\":\"solution.model\",\"fields\":[{\"na" +
				"me\":\"topic\",\"doc\":\"The topic of the vehicle position\",\"type\":\"string\"}]}");
		/// <summary>
		/// The topic of the vehicle position
		/// </summary>
		private string _topic;
		public virtual Schema Schema
		{
			get
			{
				return PositionKey._SCHEMA;
			}
		}
		/// <summary>
		/// The topic of the vehicle position
		/// </summary>
		public string topic
		{
			get
			{
				return this._topic;
			}
			set
			{
				this._topic = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.topic;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.topic = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
